//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.message;

import com.xml.megatravel.soap.model.reservation.XmlReservation;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sentToEntity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="receiverId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reservation" type="{http://www.xml.com/megatravel/soap/model/reservation}XmlReservation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sentToEntity",
    "content",
    "reservationId"
})
@XmlRootElement(name = "createMessageRequest")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateMessageRequest {

    @XmlElement(required = true)
    protected String sentToEntity;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    protected String reservationId;

    /**
     * Gets the value of the sentToEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentToEntity() {
        return sentToEntity;
    }

    /**
     * Sets the value of the sentToEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentToEntity(String value) {
        this.sentToEntity = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlReservation }
     *     
     */
    public String getReservationId() {
        return reservationId;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlReservation }
     *     
     */
    public void setReservationId(String value) {
        this.reservationId = value;
    }

}
