//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.xml.megatravel.soap.model.base.XmlBase;
import com.xml.megatravel.soap.model.reservation.XmlReservation;
import com.xml.megatravel.soap.model.user.XmlUser;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;


/**
 * <p>Java class for XmlMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.xml.com/megatravel/soap/model/base}XmlBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sender" type="{http://www.xml.com/megatravel/soap/model/user}XmlUser"/&gt;
 *         &lt;element name="receiverId"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="36"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sendToEntity"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="FOR_ADMIN"/&gt;
 *               &lt;enumeration value="FOR_AGENT"/&gt;
 *               &lt;enumeration value="FOR_USER"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="content"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1024"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="reservation" type="{http://www.xml.com/megatravel/soap/model/reservation}XmlReservation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlMessage", propOrder = {
    "sendToEntity",
    "content",
    "reservation"
})
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class XmlMessage
    extends XmlBase
{

    @XmlElement(required = true)
    protected String sendToEntity;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    protected XmlReservation reservation;

    /**
     * Gets the value of the sendToEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendToEntity() {
        return sendToEntity;
    }

    /**
     * Sets the value of the sendToEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendToEntity(String value) {
        this.sendToEntity = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlReservation }
     *     
     */
    public XmlReservation getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlReservation }
     *     
     */
    public void setReservation(XmlReservation value) {
        this.reservation = value;
    }

}
