//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.megatravel.soap.model.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetServicesRequest_QNAME = new QName("http://www.xml.com/megatravel/soap/model/service", "getServicesRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.megatravel.soap.model.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetServicesRequest }
     *
     */
    public GetServicesRequest createGetServicesRequest() {
        return new GetServicesRequest();
    }

    /**
     * Create an instance of {@link GetServicesResponse }
     * 
     */
    public GetServicesResponse createGetServicesResponse() {
        return new GetServicesResponse();
    }

    /**
     * Create an instance of {@link XmlService }
     * 
     */
    public XmlService createXmlService() {
        return new XmlService();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.com/megatravel/soap/model/service", name = "getServicesRequest")
    public JAXBElement<Object> createGetServicesRequest(Object value) {
        return new JAXBElement<Object>(_GetServicesRequest_QNAME, Object.class, null, value);
    }

}
