//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.reservation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.megatravel.soap.model.reservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetReservationsRequest_QNAME = new QName("http://www.xml.com/megatravel/soap/model/reservation", "getReservationsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.megatravel.soap.model.reservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link XmlReservation }
     * 
     */
    public XmlReservation createXmlReservation() {
        return new XmlReservation();
    }

    /**
     * Create an instance of {@link GetReservationsResponse }
     * 
     */
    public GetReservationsResponse createGetReservationsResponse() {
        return new GetReservationsResponse();
    }

    /**
     * Create an instance of {@link UpdateReservationStatusRequest }
     * 
     */
    public UpdateReservationStatusRequest createUpdateReservationStatusRequest() {
        return new UpdateReservationStatusRequest();
    }

    /**
     * Create an instance of {@link GetReservationsRequest }
     *
     */
    public GetReservationsRequest createGetReservationsRequest() {
        return new GetReservationsRequest();
    }

    /**
     * Create an instance of {@link UpdateReservationStatusResponse }
     * 
     */
    public UpdateReservationStatusResponse createUpdateReservationStatusResponse() {
        return new UpdateReservationStatusResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml.com/megatravel/soap/model/reservation", name = "getReservationsRequest")
    public JAXBElement<Object> createGetReservationsRequest(Object value) {
        return new JAXBElement<Object>(_GetReservationsRequest_QNAME, Object.class, null, value);
    }

}
