//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.propertyservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.xml.megatravel.soap.model.base.XmlBase;
import com.xml.megatravel.soap.model.property.XmlProperty;
import com.xml.megatravel.soap.model.service.XmlService;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;


/**
 * <p>Java class for XmlPropertyService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlPropertyService"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.xml.com/megatravel/soap/model/base}XmlBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="property" type="{http://www.xml.com/megatravel/soap/model/property}XmlProperty"/&gt;
 *         &lt;element name="service" type="{http://www.xml.com/megatravel/soap/model/service}XmlService"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlPropertyService", propOrder = {
    "property",
    "service"
})
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class XmlPropertyService
    extends XmlBase
{

    @XmlElement
    protected XmlProperty property;
    @XmlElement(required = true)
    protected XmlService service;

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link XmlProperty }
     *     
     */
    public XmlProperty getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlProperty }
     *     
     */
    public void setProperty(XmlProperty value) {
        this.property = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link XmlService }
     *     
     */
    public XmlService getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlService }
     *     
     */
    public void setService(XmlService value) {
        this.service = value;
    }

}
