
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application.name: services-microservice
  main.allow-bean-definition-overriding: true

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
server.port: 8082

properties:
