spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate.ddl-auto: update

server.servlet.context-path: /api

properties:
  apiUrl: '/api'
  jwtSecret: m3g4tr4v3ls3cr1111t
  jwtExpirationInMs: 604800000
  maxAgeSecs: 3600
  frontBaseUrl: 'http://localhost:4200'
  amazon:
    accessKey: 'AKIAVYSGRUGO5LYMQHDJ'
    secretKey: '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'
    region: 'eu-central-1'
    s3Endpoint: 'https://s3.eu-central-1.amazonaws.com/'
    bucket: 'megatravel'