//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.rating;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.xml.megatravel.soap.model.base.XmlBase;
import com.xml.megatravel.soap.model.reservation.XmlReservation;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;


/**
 * <p>Java class for XmlRating complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlRating"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.xml.com/megatravel/soap/model/base}XmlBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reservation" type="{http://www.xml.com/megatravel/soap/model/reservation}XmlReservation"/&gt;
 *         &lt;element name="overallRating" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="staffRating" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="servicesRating" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="comment"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="isCommentReviewed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isCommentApproved" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlRating", propOrder = {
    "reservation",
    "overallRating",
    "staffRating",
    "servicesRating",
    "comment",
    "isCommentReviewed",
    "isCommentApproved"
})
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class XmlRating
    extends XmlBase
{

    @XmlElement(required = true)
    protected XmlReservation reservation;
    protected int overallRating;
    protected int staffRating;
    protected int servicesRating;
    @XmlElement(required = true)
    protected String comment;
    protected boolean isCommentReviewed;
    protected boolean isCommentApproved;

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlReservation }
     *     
     */
    public XmlReservation getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlReservation }
     *     
     */
    public void setReservation(XmlReservation value) {
        this.reservation = value;
    }

    /**
     * Gets the value of the overallRating property.
     * 
     */
    public int getOverallRating() {
        return overallRating;
    }

    /**
     * Sets the value of the overallRating property.
     * 
     */
    public void setOverallRating(int value) {
        this.overallRating = value;
    }

    /**
     * Gets the value of the staffRating property.
     * 
     */
    public int getStaffRating() {
        return staffRating;
    }

    /**
     * Sets the value of the staffRating property.
     * 
     */
    public void setStaffRating(int value) {
        this.staffRating = value;
    }

    /**
     * Gets the value of the servicesRating property.
     * 
     */
    public int getServicesRating() {
        return servicesRating;
    }

    /**
     * Sets the value of the servicesRating property.
     * 
     */
    public void setServicesRating(int value) {
        this.servicesRating = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the isCommentReviewed property.
     * 
     */
    public boolean isIsCommentReviewed() {
        return isCommentReviewed;
    }

    /**
     * Sets the value of the isCommentReviewed property.
     * 
     */
    public void setIsCommentReviewed(boolean value) {
        this.isCommentReviewed = value;
    }

    /**
     * Gets the value of the isCommentApproved property.
     * 
     */
    public boolean isIsCommentApproved() {
        return isCommentApproved;
    }

    /**
     * Sets the value of the isCommentApproved property.
     * 
     */
    public void setIsCommentApproved(boolean value) {
        this.isCommentApproved = value;
    }

}
