
info.component: Zuul Proxy

zuul:
    sensitiveHeaders: Cookie,Set-Cookie
    host:
        connect-timeout-millis: 30000
    routes:
        reservations-microservice:
            path: reservations/**
            service-id: reservations-microservice
        services-microservice:
            path: services/**
            service-id: services-microservice
        main-backend:
            path: api/**
            service-id: main-backend

eureka.client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true

server.port: 8765
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000