spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    ##TODO: change this to validate once we start using migrations
    hibernate.ddl-auto: update

server.servlet.context-path: /api

properties:
  apiUrl: '/api'
  jwtSecret: m3g4tr4v3ls3cr1111t
  jwtExpirationInMs: 604800000
  maxAgeSecs: 3600
  frontBaseUrl: 'http://localhost:4200'