//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.property;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.megatravel.soap.model.property package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.megatravel.soap.model.property
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreatePropertyRequest }
     * 
     */
    public CreatePropertyRequest createCreatePropertyRequest() {
        return new CreatePropertyRequest();
    }

    /**
     * Create an instance of {@link AddressRequest }
     * 
     */
    public AddressRequest createAddressRequest() {
        return new AddressRequest();
    }

    /**
     * Create an instance of {@link CreatePropertyResponse }
     * 
     */
    public CreatePropertyResponse createCreatePropertyResponse() {
        return new CreatePropertyResponse();
    }

    /**
     * Create an instance of {@link XmlProperty }
     * 
     */
    public XmlProperty createXmlProperty() {
        return new XmlProperty();
    }

    /**
     * Create an instance of {@link GetPropertiesResponse }
     * 
     */
    public GetPropertiesResponse createGetPropertiesResponse() {
        return new GetPropertiesResponse();
    }

    public GetPropertiesRequest createGetPropertiesRequest() {
        return new GetPropertiesRequest();
    }

}
