//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:37:40 PM CEST 
//


package com.xml.megatravel.soap.model.property;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import com.xml.megatravel.soap.model.address.XmlAddress;
import com.xml.megatravel.soap.model.agent.XmlAgent;
import com.xml.megatravel.soap.model.base.XmlBase;
import com.xml.megatravel.soap.model.category.XmlCategory;
import com.xml.megatravel.soap.model.propertyservice.XmlPropertyService;
import com.xml.megatravel.soap.model.reservation.XmlReservation;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;


/**
 * <p>Java class for XmlProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlProperty"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.xml.com/megatravel/soap/model/base}XmlBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="128"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="description"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="category" type="{http://www.xml.com/megatravel/soap/model/category}XmlCategory"/&gt;
 *         &lt;element name="stars"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxInclusive value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numberOfPeople" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="numberOfCancellationDays" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="summerPrice" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="winterPrice" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="springPrice" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="autumnPrice" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="type" type="{http://www.xml.com/megatravel/soap/model/type}XmlType"/&gt;
 *         &lt;element name="address" type="{http://www.xml.com/megatravel/soap/model/address}XmlAddress"/&gt;
 *         &lt;element name="agent" type="{http://www.xml.com/megatravel/soap/model/agent}XmlAgent"/&gt;
 *         &lt;element name="reservations" type="{http://www.xml.com/megatravel/soap/model/reservation}XmlReservation" maxOccurs="unbounded"/&gt;
 *         &lt;element name="propertyServices" type="{http://www.xml.com/megatravel/soap/model/propertyservice}XmlPropertyService" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(name = "XmlProperty", propOrder = {
    "name",
    "description",
    "category",
    "stars",
    "numberOfPeople",
    "numberOfCancellationDays",
    "summerPrice",
    "winterPrice",
    "springPrice",
    "autumnPrice",
    "type",
    "address",
    "agent",
    "reservations",
    "propertyServices"
})
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class XmlProperty
    extends XmlBase
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String category;
    protected int stars;
    protected int numberOfPeople;
    protected int numberOfCancellationDays;
    protected double summerPrice;
    protected double winterPrice;
    protected double springPrice;
    protected double autumnPrice;
    @XmlElement(required = true)
    protected com.xml.megatravel.soap.model.type.XmlType type;
    @XmlElement(required = true)
    protected XmlAddress address;
    @XmlElement(required = true)
    protected XmlAgent agent;
    @XmlElement
    protected List<XmlReservation> reservations;
    @XmlElement(required = true)
    protected List<XmlPropertyService> propertyServices;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCategory }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCategory }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the stars property.
     * 
     */
    public int getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     */
    public void setStars(int value) {
        this.stars = value;
    }

    /**
     * Gets the value of the numberOfPeople property.
     * 
     */
    public int getNumberOfPeople() {
        return numberOfPeople;
    }

    /**
     * Sets the value of the numberOfPeople property.
     * 
     */
    public void setNumberOfPeople(int value) {
        this.numberOfPeople = value;
    }

    /**
     * Gets the value of the numberOfCancellationDays property.
     * 
     */
    public int getNumberOfCancellationDays() {
        return numberOfCancellationDays;
    }

    /**
     * Sets the value of the numberOfCancellationDays property.
     * 
     */
    public void setNumberOfCancellationDays(int value) {
        this.numberOfCancellationDays = value;
    }

    /**
     * Gets the value of the summerPrice property.
     * 
     */
    public double getSummerPrice() {
        return summerPrice;
    }

    /**
     * Sets the value of the summerPrice property.
     * 
     */
    public void setSummerPrice(double value) {
        this.summerPrice = value;
    }

    /**
     * Gets the value of the winterPrice property.
     * 
     */
    public double getWinterPrice() {
        return winterPrice;
    }

    /**
     * Sets the value of the winterPrice property.
     * 
     */
    public void setWinterPrice(double value) {
        this.winterPrice = value;
    }

    /**
     * Gets the value of the springPrice property.
     * 
     */
    public double getSpringPrice() {
        return springPrice;
    }

    /**
     * Sets the value of the springPrice property.
     * 
     */
    public void setSpringPrice(double value) {
        this.springPrice = value;
    }

    /**
     * Gets the value of the autumnPrice property.
     * 
     */
    public double getAutumnPrice() {
        return autumnPrice;
    }

    /**
     * Sets the value of the autumnPrice property.
     * 
     */
    public void setAutumnPrice(double value) {
        this.autumnPrice = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link com.xml.megatravel.soap.model.type.XmlType }
     *     
     */
    public com.xml.megatravel.soap.model.type.XmlType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.xml.megatravel.soap.model.type.XmlType }
     *     
     */
    public void setType(com.xml.megatravel.soap.model.type.XmlType value) {
        this.type = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAddress }
     *     
     */
    public XmlAddress getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAddress }
     *     
     */
    public void setAddress(XmlAddress value) {
        this.address = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAgent }
     *     
     */
    public XmlAgent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAgent }
     *     
     */
    public void setAgent(XmlAgent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlReservation }
     * 
     * 
     */
    public List<XmlReservation> getReservations() {
        if (reservations == null) {
            reservations = new ArrayList<XmlReservation>();
        }
        return this.reservations;
    }

    /**
     * Gets the value of the propertyServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlPropertyService }
     * 
     * 
     */
    public List<XmlPropertyService> getPropertyServices() {
        if (propertyServices == null) {
            propertyServices = new ArrayList<XmlPropertyService>();
        }
        return this.propertyServices;
    }

}
